# Generated by Django 4.1 on 2025-10-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musician", "0002_alter_musician_date_of_applying"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musician",
            name="date_of_applying",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
