# Generated by Django 4.1 on 2025-10-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musician", "0003_alter_musician_date_of_applying"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musician",
            options={"verbose_name": "Musician"},
        ),
    ]
